{"name": "Проверка статуса ответа с кодом 401 при выполнении запоса на получение заказовнеавторизованного пользователя.", "status": "passed", "description": "Выполняем запрос на получение заказов для неваторизованного пользователя и проверяем,что приходит статус ответа с кодом 401 и тело ответа содержит сообщение об ошибке", "start": 1715541202288, "stop": 1715541202490, "uuid": "b08d7e55-599f-4e32-9aa5-8b8fb1d5d438", "historyId": "eef9474c7c87e878bc8e3603626dde9a", "testCaseId": "eef9474c7c87e878bc8e3603626dde9a", "fullName": "tests.orders.test_get_orders.TestOrdersUser#test_get_order_unauthorized_user", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestOrdersUser"}, {"name": "host", "value": "ubuntupc-ThinkPad-T14-Gen-2i"}, {"name": "thread", "value": "315926-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_get_orders"}]}